### PR TITLE
Spliting the JoinGame and CreateGame commands and enabling SetupPorts to be called from the Coordinator

### PR DESCRIPTION
**Pull request by Cryptyc**

### CODE REVIEW

**Comment by AnthonyBrunasso** [comment]
Hey there! 

What is the intent of check_single in the SetupPorts function? Also the curly braces are still not correct in that function :p.

**Comment by Cryptyc** [comment]
Sorry, thought I caught all those braces lol, I'll fix that

The purpose of check_single is to maintiain the check for just a single agent vs computer, where we don't need the ports set up.  I wanted to maintain the functionality as much as possible.

When setting up the proxy, the clients will only know about the single participant, so in the normal SetupPorts function, it wouldn't normally set up the ports structure.  We need a way to bypass this and still set up the ports structure even when the local coordinator only knows of one agent, this seems like the easiest way to do that.

**Comment by AnthonyBrunasso** [comment]
That makes sense. How are you dealing with sharing the ports between the two running processes? As in, how does agent 2 know the correct ports for agent 1 if they are on different processes. Is it just in preset in code?

**Comment by Cryptyc** [comment]
The plan is to pass that in as setup parameters when launching the clients from the manager, at least for the first version.  Eventually I want the clients to download it from a web service when setting up, but that might come in a later revision.

**Comment by AnthonyBrunasso** [comment]
Perfect! Thank you for your contribution.

**Pull request merged**
